[general]
interface = "eth0"
stats_interval_ms = 1000

[default_rule]
egress_rate_bps = 1048576    # 1 MB/s
ingress_rate_bps = 5242880   # 5 MB/s
priority = 8

[[rules]]
name = "user-jrestivo"
user = "jrestivo"
priority = 1                  # highest priority

[[rules]]
name = "docker-torrents"
container_name = "qbittorrent"
egress_rate_bps = 524288
ingress_rate_bps = 10485760
priority = 9
